---
layout: default
---

 <div class="refnamediv">
  <h1 class="refname">SolrQuery::__construct</h1>
  <p class="verinfo">(PECL solr &gt;= 0.9.2)</p><p class="refpurpose"><span class="refname">SolrQuery::__construct</span> &#x2014; <span class="dc-title">Constructor</span></p>

 </div>

 <div class="refsect1 description" id="refsect1-solrquery.construct-description">
  <h3 class="title">Description</h3>
  <div class="methodsynopsis dc-description">
   <span class="modifier">public</span> <span class="methodname"><strong>SolrQuery::__construct</strong></span>
    ([ <span class="methodparam"><span class="type">string</span> <code class="parameter">$q</code></span>
  ] )</div>

  <p class="para rdfs-comment">
   Constructor.
  </p>

 </div>


 <div class="refsect1 parameters" id="refsect1-solrquery.construct-parameters">
  <h3 class="title">Parameters</h3>
  <p class="para">
   <dl>

    
     <dt>
<code class="parameter">q</code></dt>

     <dd>

      <p class="para">
       Optional search query
      </p>
     </dd>

    
   </dl>

  </p>
 </div>


 <div class="refsect1 returnvalues" id="refsect1-solrquery.construct-returnvalues">
  <h3 class="title">Return Values</h3>
  <p class="para">
   None
  </p>
 </div>

<div class="refsect1 errors" id="refsect1-solrquery.construct-errors">
  <h3 class="title">Errors/Exceptions</h3>
  <p class="para">
   Emits <a href="class.solrillegalargumentexception.html" class="classname">SolrIllegalArgumentException</a> in case of an invalid parameter was passed.
  </p>
 </div>

 <div class="refsect1 changelog" id="refsect1-solrquery.construct-changelog">
  <h3 class="title">Changelog</h3>
  <p class="para">
   <table class="doctable informaltable">
    
     <thead>
      <tr>
       <th>Version</th>
       <th>Description</th>
      </tr>

     </thead>

     <tbody class="tbody">
      <tr>
       <td>2.0.0</td>
       <td>
        If <code class="parameter">q</code> was invalid, then a
        <a href="class.solrillegalargumentexception.html" class="classname">SolrIllegalArgumentException</a> is now thrown. Previously an error was emitted.
       </td>
      </tr>

     </tbody>
    
   </table>

  </p>
 </div>

